export const WATCHLIST_VENUES = [
  "coex-samseong",
  "coex-magok",
  "multi",
] as const;
export type WatchlistVenue = (typeof WATCHLIST_VENUES)[number];

export const WATCHLIST_CONFIDENCE = [
  "confirmed",
  "included_by_scale",
] as const;
export type WatchlistConfidence = (typeof WATCHLIST_CONFIDENCE)[number];

export interface RecurringExhibitionWatchlistItem {
  id: string;
  slug: string;
  name: string;
  category: string;
  primaryVenue: WatchlistVenue;
  venues: Exclude<WatchlistVenue, "multi">[];
  recurrence: string;
  audienceFloor: number;
  lastVerifiedAttendance?: number;
  attendanceYear?: number;
  attendanceNote: string;
  confidence: WatchlistConfidence;
  trackingStatus: "active" | "paused" | "archived";
  sourceUrls: string[];
  notes: string;
}

export const RECURRING_EXHIBITION_WATCHLIST = [
  {
    id: "rew_sibf",
    slug: "seoul-international-book-fair",
    name: "서울국제도서전",
    category: "도서",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "매년",
    audienceFloor: 10000,
    lastVerifiedAttendance: 150000,
    attendanceYear: 2025,
    attendanceNote: "2025년 15만 명 이상 방문.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: ["https://www.coex.co.kr/coex-40th-anniversary-history/"],
    notes: "국내 최대급 도서전. Roam의 기존 SIBF 운영 데이터와 연결 우선.",
  },
  {
    id: "rew_seoul_cafe_show",
    slug: "seoul-cafe-show",
    name: "서울카페쇼",
    category: "카페/F&B",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "매년",
    audienceFloor: 10000,
    lastVerifiedAttendance: 127745,
    attendanceYear: 2025,
    attendanceNote: "2025년 약 12.8만~15만 명 보도.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: [
      "https://www.coex.co.kr/exhibitions/%EC%A0%9C24%ED%9A%8C-%EC%84%9C%EC%9A%B8%EC%B9%B4%ED%8E%98%EC%87%BC/",
      "https://economist.co.kr/article/view/ecn202512020058",
    ],
    notes: "카페·커피 업계 대형 B2B/B2C 행사.",
  },
  {
    id: "rew_seoul_living_design_fair",
    slug: "seoul-living-design-fair",
    name: "서울리빙디자인페어",
    category: "리빙/디자인",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "매년",
    audienceFloor: 10000,
    lastVerifiedAttendance: 100000,
    attendanceYear: 2024,
    attendanceNote: "2024년 약 10만 명.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: [
      "https://www.thereport.co.kr/news/articleView.html?idxno=47125",
      "https://business.coex.co.kr/post-exhibitions/%EC%84%9C%EC%9A%B8%EB%A6%AC%EB%B9%99%EB%94%94%EC%9E%90%EC%9D%B8%ED%8E%98%EC%96%B4/",
    ],
    notes: "마곡 파생 행사와 별도로 삼성 코엑스 본행사를 추적.",
  },
  {
    id: "rew_kiaf_seoul",
    slug: "kiaf-seoul",
    name: "Kiaf SEOUL 한국국제아트페어",
    category: "아트",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "매년",
    audienceFloor: 10000,
    lastVerifiedAttendance: 82000,
    attendanceYear: 2025,
    attendanceNote: "2025년 약 8.2만 명.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: [
      "https://www.newsis.com/view/?id=NISX20250907_0003319078",
      "https://www.coex.co.kr/exhibitions/kiaf-seoul-2025-%ED%95%9C%EA%B5%AD%EA%B5%AD%EC%A0%9C%EC%95%84%ED%8A%B8%ED%8E%98%EC%96%B4/",
    ],
    notes: "아트페어 성격상 VIP/프리뷰/일반 관람 동선 구분 필요.",
  },
  {
    id: "rew_food_week_korea",
    slug: "food-week-korea",
    name: "푸드위크 코리아 / 서울국제식품산업전",
    category: "식품",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "매년",
    audienceFloor: 10000,
    lastVerifiedAttendance: 52754,
    attendanceYear: 2025,
    attendanceNote: "2025년 52,754명.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: [
      "https://www.foodweek.co.kr/last-exhibition?hl=ko",
      "https://business.coex.co.kr/coex-40th-anniversary-history/",
    ],
    notes: "식품 B2B/B2C 혼합 전시.",
  },
  {
    id: "rew_education_korea",
    slug: "education-korea",
    name: "대한민국 교육박람회",
    category: "교육",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "매년",
    audienceFloor: 10000,
    lastVerifiedAttendance: 60302,
    attendanceYear: 2026,
    attendanceNote: "2026년 60,302명.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: ["https://www.educationkorea.kr/show-result"],
    notes: "교육기관·에듀테크·학부모 관람객이 섞이는 전시.",
  },
  {
    id: "rew_seoul_coffee_expo",
    slug: "seoul-coffee-expo",
    name: "서울커피엑스포",
    category: "커피",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "매년",
    audienceFloor: 10000,
    lastVerifiedAttendance: 41443,
    attendanceYear: 2026,
    attendanceNote: "2026년 41,443명.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: ["https://coffeexpo2026.ems.coex.co.kr/history?hl=ko"],
    notes: "서울카페쇼와 별도 회차로 추적.",
  },
  {
    id: "rew_spoex",
    slug: "spoex",
    name: "SPOEX 서울국제스포츠레저산업전",
    category: "스포츠/레저",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "매년",
    audienceFloor: 10000,
    lastVerifiedAttendance: 43602,
    attendanceYear: 2025,
    attendanceNote: "2025년 43,602명.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: [
      "https://www.spoex.com/main/intro/result",
      "https://spobiz.kspo.or.kr/front/html/html.do?sitePage=supportInfoDetail01&tab=tab1&topMenuSeq=1",
    ],
    notes: "스포츠·레저 장비 체험형 부스 가능성이 높음.",
  },
  {
    id: "rew_seoul_illustration_fair",
    slug: "seoul-illustration-fair",
    name: "서울일러스트레이션페어",
    category: "일러스트",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "연 2회 성격",
    audienceFloor: 10000,
    lastVerifiedAttendance: 70000,
    attendanceNote: "매회 약 7만 명 규모로 소개.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: [
      "https://culture.seoul.go.kr/culture/culture/cultureEvent/view.do?cultcode=156193&menuNo=200008",
    ],
    notes: "작가/브랜드 부스 밀도가 높아 개인 취향 추천과 잘 맞는 전시.",
  },
  {
    id: "rew_k_pet_fair_seoul",
    slug: "k-pet-fair-seoul",
    name: "케이펫페어 서울",
    category: "반려동물",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "반복 개최",
    audienceFloor: 10000,
    lastVerifiedAttendance: 21539,
    attendanceYear: 2025,
    attendanceNote: "2025년 21,539명.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: ["https://k-pet.co.kr/portfolio-items/25petco_report/"],
    notes: "동반/체험/구매 목적을 함께 보는 전시.",
  },
  {
    id: "rew_befe_baby_fair",
    slug: "befe-baby-fair",
    name: "베페 베이비페어",
    category: "베이비",
    primaryVenue: "multi",
    venues: ["coex-samseong", "coex-magok"],
    recurrence: "정기 개최",
    audienceFloor: 10000,
    lastVerifiedAttendance: 50000,
    attendanceNote: "공식 소개 기준 매회 약 5만 명 이상 규모.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: ["https://www.magok.befe.co.kr/exhibition"],
    notes: "삼성 코엑스와 코엑스마곡 양쪽 회차를 모두 추적.",
  },
  {
    id: "rew_cobe_baby_fair",
    slug: "cobe-baby-fair",
    name: "코베 베이비페어",
    category: "베이비",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "정기 개최",
    audienceFloor: 10000,
    attendanceYear: 2026,
    attendanceNote: "회차별 수치는 약하지만 대형 베이비페어로 포함 결정.",
    confidence: "included_by_scale",
    trackingStatus: "active",
    sourceUrls: ["https://www.cobe.co.kr/"],
    notes: "사용자 결정으로 추적 목록에 포함. 회차별 참관객 수는 다음 조사 때 보강.",
  },
  {
    id: "rew_seoul_early_childhood_education_fair",
    slug: "seoul-early-childhood-education-kids-fair",
    name: "서울국제유아교육전&키즈페어, 유교전",
    category: "유아/키즈",
    primaryVenue: "coex-samseong",
    venues: ["coex-samseong"],
    recurrence: "정기 개최",
    audienceFloor: 10000,
    attendanceYear: 2026,
    attendanceNote: "코엑스 A홀 대형 전시, 약 500부스 규모로 포함 결정.",
    confidence: "included_by_scale",
    trackingStatus: "active",
    sourceUrls: [
      "https://akei.or.kr/bbs/board.php?bo_table=schedule&page=6&wr_id=104002",
      "https://segefairsglobal.com/home",
    ],
    notes: "사용자 결정으로 추적 목록에 포함. 방문객 수 공개 근거는 다음 조사 때 보강.",
  },
  {
    id: "rew_magok_living_design_fair",
    slug: "magok-living-design-fair",
    name: "마곡리빙디자인페어 / 서울리빙디자인페어 in 마곡",
    category: "리빙/디자인",
    primaryVenue: "coex-magok",
    venues: ["coex-magok"],
    recurrence: "2024 첫 개최 후 반복",
    audienceFloor: 10000,
    lastVerifiedAttendance: 43000,
    attendanceYear: 2024,
    attendanceNote: "2024년 약 43,000명.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: [
      "https://www.segyebiz.com/newsView/20241202508603",
      "https://m.ekn.kr/view.php?key=20250911025256005",
      "https://business.coex.co.kr/",
    ],
    notes: "코엑스마곡 대표 리빙 전시로 별도 추적.",
  },
  {
    id: "rew_k_pet_fair_magok",
    slug: "k-pet-fair-magok",
    name: "케이펫페어 마곡",
    category: "반려동물",
    primaryVenue: "coex-magok",
    venues: ["coex-magok"],
    recurrence: "반복 개최",
    audienceFloor: 10000,
    lastVerifiedAttendance: 12967,
    attendanceYear: 2025,
    attendanceNote: "2025년 12,967명.",
    confidence: "confirmed",
    trackingStatus: "active",
    sourceUrls: [
      "https://k-pet.co.kr/portfolio-items/25petm_report/",
      "https://k-pet.co.kr/information/exhibition-scheduled-all/26pet_magok/",
    ],
    notes: "마곡 회차는 서울 코엑스 회차와 별도 운영 데이터로 추적.",
  },
] as const satisfies readonly RecurringExhibitionWatchlistItem[];

export function listActiveRecurringExhibitionWatchlist() {
  return RECURRING_EXHIBITION_WATCHLIST.filter(
    (item) => item.trackingStatus === "active",
  );
}
