// Generates supabase/seed.sql from the canonical mock seed so the hosted DB
// matches mock mode exactly. Run: node scripts/gen-seed.mjs
import { build } from "esbuild";
import { writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

async function bundle(entry) {
  const out = join(mkdtempSync(join(tmpdir(), "seed-")), "seed.mjs");
  await build({
    entryPoints: [entry],
    bundle: true,
    format: "esm",
    platform: "node",
    outfile: out,
    alias: { "@": "./src" },
    logLevel: "error",
  });
  return import(out);
}

const seed = await bundle("src/lib/mock/seed.ts");
// SIF(서울일러스트레이션페어) — SIBF와 공존하는 두 번째 전시. 같은 seed.sql에
// 함께 실어 호스티드 DB가 mock 멀티 전시와 패리티를 이룬다.
const sif = await bundle("src/lib/mock/seed-sif.ts");

// 여러 전시를 함께 emit하기 위한 합집합. events/kits/reviews/posts는 SIBF만 보유.
const allExhibitions = [seed.exhibition, sif.sifExhibition];
const allHalls = [...seed.halls, ...sif.sifHalls];
const allCategories = [...seed.categories, ...sif.sifCategories];
const allBooths = [...seed.booths, ...sif.sifBooths];

// 이관 텍스트(작가 소개 등)에 U+2028/U+2029(LS/PS) 같은 비정상 줄종결자가 섞여
// 들어온다. Postgres는 받지만 에디터가 경고하고 일부 도구가 깨지므로 개행으로 치환.
const clean = (s) => s.replace(/[\u2028\u2029]/g, "\n");
const q = (v) =>
  v === undefined || v === null
    ? "null"
    : `'${clean(String(v)).replace(/'/g, "''")}'`;
const jb = (v) => `'${clean(JSON.stringify(v)).replace(/'/g, "''")}'::jsonb`;
const n = (v) => (v === undefined || v === null ? "null" : String(v));
const b = (v) => (v ? "true" : "false");

const lines = [];
lines.push("-- Generated by scripts/gen-seed.mjs — do not edit by hand.");
lines.push("-- 2026 Seoul International Book Fair seed (parity with mock).");
lines.push("");

// organizer (FK target for exhibition.organizer_id) — 전시별 주최자.
lines.push("insert into organizer (id, email, name) values");
lines.push(
  [
    `  (${q(seed.exhibition.organizerId)}, 'sibf@sibf.kr', '서울국제도서전 사무국')`,
    `  (${q(sif.sifExhibition.organizerId)}, 'sif@ocreo.kr', '서울일러스트레이션페어 사무국')`,
  ].join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

lines.push(
  "insert into exhibition (id, slug, name, venue, description, start_date, end_date, cover_image_url, map_image_url, map_width, map_height, tips, organizer_id, created_at) values",
);
lines.push(
  allExhibitions
    .map(
      (e) =>
        `  (${q(e.id)}, ${q(e.slug)}, ${q(e.name)}, ${q(e.venue)}, ${q(e.description)}, ${q(e.startDate)}, ${q(e.endDate)}, ${q(e.coverImageUrl)}, ${q(e.mapImageUrl)}, ${n(e.mapWidth)}, ${n(e.mapHeight)}, ${jb(e.tips)}, ${q(e.organizerId)}, ${q(e.createdAt)})`,
    )
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

lines.push("insert into hall (id, exhibition_id, name, floor, sort) values");
lines.push(
  allHalls
    .map((h) => `  (${q(h.id)}, ${q(h.exhibitionId)}, ${q(h.name)}, ${n(h.floor)}, ${n(h.sort)})`)
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

lines.push("insert into category (id, slug, name, color, icon) values");
lines.push(
  allCategories
    .map((c) => `  (${q(c.id)}, ${q(c.slug)}, ${q(c.name)}, ${q(c.color)}, ${q(c.icon)})`)
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

lines.push(
  "insert into booth (id, exhibition_id, hall_id, category_id, code, kind, name, company, aliases, description, long_description, images, logo_url, instagram_url, website_url, tags, x, y, popularity, created_at) values",
);
lines.push(
  allBooths
    .map(
      (t) =>
        `  (${q(t.id)}, ${q(t.exhibitionId)}, ${q(t.hallId)}, ${q(t.categoryId)}, ${q(t.code)}, ${q(t.kind ?? "exhibitor")}, ${q(t.name)}, ${q(t.company)}, ${jb(t.aliases ?? [])}, ${q(t.description)}, ${q(t.longDescription)}, ${jb(t.images)}, ${q(t.logoUrl)}, ${q(t.instagramUrl)}, ${q(t.websiteUrl)}, ${jb(t.tags)}, ${n(t.x)}, ${n(t.y)}, ${n(t.popularity)}, ${q(t.createdAt)})`,
    )
    .join(",\n"),
);
// 시드 데이터라 재적용 시 최신 소스로 갱신되도록 do update(이미지·링크·소개 등
// 후속 이관이 기존 행에 반영되게). 키(id) 제외 전 컬럼 덮어씀.
lines.push(
  "on conflict (id) do update set " +
    [
      "exhibition_id",
      "hall_id",
      "category_id",
      "code",
      "kind",
      "name",
      "company",
      "aliases",
      "description",
      "long_description",
      "images",
      "logo_url",
      "instagram_url",
      "website_url",
      "tags",
      "x",
      "y",
      "popularity",
    ]
      .map((c) => `${c} = excluded.${c}`)
      .join(", ") +
    ";",
);
lines.push("");

// booth_enrichment — 수동 주입 추가정보가 있는 부스만(현재 비어 있으면 블록 생략).
const enriched = allBooths.filter((t) => t.enrichment);
if (enriched.length) {
  lines.push(
    "insert into booth_enrichment (booth_id, goods_keywords, theme_tags, summary, tips, source_url) values",
  );
  lines.push(
    enriched
      .map(
        (t) =>
          `  (${q(t.id)}, ${jb(t.enrichment.goodsKeywords ?? [])}, ${jb(t.enrichment.themeTags ?? [])}, ${q(t.enrichment.summary)}, ${q(t.enrichment.tips)}, ${q(t.enrichment.sourceUrl)})`,
      )
      .join(",\n"),
  );
  lines.push(
    "on conflict (booth_id) do update set " +
      ["goods_keywords", "theme_tags", "summary", "tips", "source_url"]
        .map((c) => `${c} = excluded.${c}`)
        .join(", ") +
      ";",
  );
  lines.push("");
}

lines.push(
  "insert into event (id, booth_id, title, description, start_time, end_time, reward_info, capacity, tag, subtitle, speaker, standing) values",
);
lines.push(
  seed.events
    .map(
      (v) =>
        `  (${q(v.id)}, ${q(v.boothId)}, ${q(v.title)}, ${q(v.description)}, ${q(v.startTime)}, ${q(v.endTime)}, ${q(v.rewardInfo)}, ${n(v.capacity)}, ${q(v.tag)}, ${q(v.subtitle)}, ${q(v.speaker)}, ${b(v.standing)})`,
    )
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

// waiting — seed.ts에서 export 제거됨(실시간 대기는 런타임 데이터). 있으면만 emit.
const waitings = seed.waitings ?? [];
if (waitings.length) {
  lines.push(
    "insert into waiting (booth_id, enabled, queue_count, estimated_minutes, updated_at) values",
  );
  lines.push(
    waitings
      .map((w) => `  (${q(w.boothId)}, ${b(w.enabled)}, ${n(w.queueCount)}, ${n(w.estimatedMinutes)}, ${q(w.updatedAt)})`)
      .join(",\n"),
  );
  lines.push("on conflict (booth_id) do nothing;");
  lines.push("");
}

lines.push(
  "insert into welcome_kit (booth_id, enabled, name, description, image_url, remaining_count) values",
);
lines.push(
  seed.welcomeKits
    .map((k) => `  (${q(k.boothId)}, ${b(k.enabled)}, ${q(k.name)}, ${q(k.description)}, ${q(k.imageUrl)}, ${n(k.remainingCount)})`)
    .join(",\n"),
);
lines.push("on conflict (booth_id) do nothing;");
lines.push("");

lines.push(
  "insert into review (id, booth_id, session_id, comment, author_name, created_at) values",
);
lines.push(
  seed.reviews
    .map((r) => `  (${q(r.id)}, ${q(r.boothId)}, ${q(r.sessionId)}, ${q(r.comment)}, ${q(r.authorName)}, ${q(r.createdAt)})`)
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

// community_post — seed visitor_session row first to satisfy the FK.
lines.push("insert into visitor_session (id, exhibition_id, created_at, last_seen_at) values");
lines.push(`  ('seed', ${q(seed.exhibition.id)}, ${q(seed.exhibition.createdAt)}, ${q(seed.exhibition.createdAt)})`);
lines.push("on conflict (id) do nothing;");
lines.push("");

lines.push(
  "insert into community_post (id, exhibition_id, session_id, author_name, body, booth_id, created_at) values",
);
lines.push(
  seed.communityPosts
    .map((p) => `  (${q(p.id)}, ${q(p.exhibitionId)}, ${q(p.sessionId)}, ${q(p.authorName)}, ${q(p.body)}, ${q(p.boothId)}, ${q(p.createdAt)})`)
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

writeFileSync("supabase/seed.sql", lines.join("\n"));

// reset.sql = truncate 프리앰블 + seed 본문(같은 소스라 항상 동기화).
const reset = [
  "-- Roam 전체 데이터 reset + 재시드 (스키마 유지, 데이터만 교체).",
  "-- 생성: gen-seed.mjs. 적용: Supabase SQL Editor에 붙여넣고 실행.",
  "begin;",
  "truncate table",
  "  community_post, visitor_session, review, welcome_kit, waiting,",
  "  event, booth, category, hall, exhibition, organizer",
  "restart identity cascade;",
  "",
  ...lines,
  "",
  "commit;",
];
writeFileSync("supabase/reset.sql", reset.join("\n"));
console.log(
  `seed.sql written: ${allBooths.length} booths (SIBF ${seed.booths.length} + SIF ${sif.sifBooths.length}), ${seed.events.length} events, ${seed.communityPosts.length} posts`,
);
