// Generates supabase/seed.sql from the canonical mock seed so the hosted DB
// matches mock mode exactly. Run: node scripts/gen-seed.mjs
import { build } from "esbuild";
import { writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const out = join(mkdtempSync(join(tmpdir(), "seed-")), "seed.mjs");
await build({
  entryPoints: ["src/lib/mock/seed.ts"],
  bundle: true,
  format: "esm",
  platform: "node",
  outfile: out,
  alias: { "@": "./src" },
  logLevel: "error",
});
const seed = await import(out);

const q = (v) =>
  v === undefined || v === null ? "null" : `'${String(v).replace(/'/g, "''")}'`;
const jb = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const n = (v) => (v === undefined || v === null ? "null" : String(v));
const b = (v) => (v ? "true" : "false");

const lines = [];
lines.push("-- Generated by scripts/gen-seed.mjs — do not edit by hand.");
lines.push("-- 2026 Seoul International Book Fair seed (parity with mock).");
lines.push("");

// organizer (FK target for exhibition.organizer_id)
lines.push("insert into organizer (id, email, name) values");
lines.push(`  (${q(seed.exhibition.organizerId)}, 'sibf@sibf.kr', '서울국제도서전 사무국')`);
lines.push("on conflict (id) do nothing;");
lines.push("");

const e = seed.exhibition;
lines.push(
  "insert into exhibition (id, slug, name, venue, description, start_date, end_date, cover_image_url, map_image_url, map_width, map_height, tips, organizer_id, created_at) values",
);
lines.push(
  `  (${q(e.id)}, ${q(e.slug)}, ${q(e.name)}, ${q(e.venue)}, ${q(e.description)}, ${q(e.startDate)}, ${q(e.endDate)}, ${q(e.coverImageUrl)}, ${q(e.mapImageUrl)}, ${n(e.mapWidth)}, ${n(e.mapHeight)}, ${jb(e.tips)}, ${q(e.organizerId)}, ${q(e.createdAt)})`,
);
lines.push("on conflict (id) do nothing;");
lines.push("");

lines.push("insert into hall (id, exhibition_id, name, floor, sort) values");
lines.push(
  seed.halls
    .map((h) => `  (${q(h.id)}, ${q(h.exhibitionId)}, ${q(h.name)}, ${n(h.floor)}, ${n(h.sort)})`)
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

lines.push("insert into category (id, slug, name, color, icon) values");
lines.push(
  seed.categories
    .map((c) => `  (${q(c.id)}, ${q(c.slug)}, ${q(c.name)}, ${q(c.color)}, ${q(c.icon)})`)
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

lines.push(
  "insert into booth (id, exhibition_id, hall_id, category_id, code, kind, name, company, aliases, description, long_description, images, logo_url, instagram_url, website_url, tags, x, y, popularity, created_at) values",
);
lines.push(
  seed.booths
    .map(
      (t) =>
        `  (${q(t.id)}, ${q(t.exhibitionId)}, ${q(t.hallId)}, ${q(t.categoryId)}, ${q(t.code)}, ${q(t.kind ?? "exhibitor")}, ${q(t.name)}, ${q(t.company)}, ${jb(t.aliases ?? [])}, ${q(t.description)}, ${q(t.longDescription)}, ${jb(t.images)}, ${q(t.logoUrl)}, ${q(t.instagramUrl)}, ${q(t.websiteUrl)}, ${jb(t.tags)}, ${n(t.x)}, ${n(t.y)}, ${n(t.popularity)}, ${q(t.createdAt)})`,
    )
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

// booth_enrichment — 수동 주입 추가정보가 있는 부스만(현재 비어 있으면 블록 생략).
const enriched = seed.booths.filter((t) => t.enrichment);
if (enriched.length) {
  lines.push(
    "insert into booth_enrichment (booth_id, goods_keywords, theme_tags, summary, tips, source_url) values",
  );
  lines.push(
    enriched
      .map(
        (t) =>
          `  (${q(t.id)}, ${jb(t.enrichment.goodsKeywords ?? [])}, ${jb(t.enrichment.themeTags ?? [])}, ${q(t.enrichment.summary)}, ${q(t.enrichment.tips)}, ${q(t.enrichment.sourceUrl)})`,
      )
      .join(",\n"),
  );
  lines.push("on conflict (booth_id) do nothing;");
  lines.push("");
}

lines.push(
  "insert into event (id, booth_id, title, description, start_time, end_time, reward_info, capacity, tag, subtitle, speaker, standing) values",
);
lines.push(
  seed.events
    .map(
      (v) =>
        `  (${q(v.id)}, ${q(v.boothId)}, ${q(v.title)}, ${q(v.description)}, ${q(v.startTime)}, ${q(v.endTime)}, ${q(v.rewardInfo)}, ${n(v.capacity)}, ${q(v.tag)}, ${q(v.subtitle)}, ${q(v.speaker)}, ${b(v.standing)})`,
    )
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

lines.push(
  "insert into waiting (booth_id, enabled, queue_count, estimated_minutes, updated_at) values",
);
lines.push(
  seed.waitings
    .map((w) => `  (${q(w.boothId)}, ${b(w.enabled)}, ${n(w.queueCount)}, ${n(w.estimatedMinutes)}, ${q(w.updatedAt)})`)
    .join(",\n"),
);
lines.push("on conflict (booth_id) do nothing;");
lines.push("");

lines.push(
  "insert into welcome_kit (booth_id, enabled, name, description, image_url, remaining_count) values",
);
lines.push(
  seed.welcomeKits
    .map((k) => `  (${q(k.boothId)}, ${b(k.enabled)}, ${q(k.name)}, ${q(k.description)}, ${q(k.imageUrl)}, ${n(k.remainingCount)})`)
    .join(",\n"),
);
lines.push("on conflict (booth_id) do nothing;");
lines.push("");

lines.push(
  "insert into review (id, booth_id, session_id, rating, comment, author_name, created_at) values",
);
lines.push(
  seed.reviews
    .map((r) => `  (${q(r.id)}, ${q(r.boothId)}, ${q(r.sessionId)}, ${n(r.rating)}, ${q(r.comment)}, ${q(r.authorName)}, ${q(r.createdAt)})`)
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

// community_post — seed visitor_session row first to satisfy the FK.
lines.push("insert into visitor_session (id, exhibition_id, created_at, last_seen_at) values");
lines.push(`  ('seed', ${q(seed.exhibition.id)}, ${q(seed.exhibition.createdAt)}, ${q(seed.exhibition.createdAt)})`);
lines.push("on conflict (id) do nothing;");
lines.push("");

lines.push(
  "insert into community_post (id, exhibition_id, session_id, author_name, body, booth_id, created_at) values",
);
lines.push(
  seed.communityPosts
    .map((p) => `  (${q(p.id)}, ${q(p.exhibitionId)}, ${q(p.sessionId)}, ${q(p.authorName)}, ${q(p.body)}, ${q(p.boothId)}, ${q(p.createdAt)})`)
    .join(",\n"),
);
lines.push("on conflict (id) do nothing;");
lines.push("");

writeFileSync("supabase/seed.sql", lines.join("\n"));
console.log(
  `seed.sql written: ${seed.booths.length} booths, ${seed.events.length} events, ${seed.communityPosts.length} posts`,
);
