-- 0022: booth_enrichment 근거 카드 저작 데이터 주입(16부스). 0021 컬럼 + enrichment JSON 패리티.
-- recommendationReasons/valueTags 등 저작 필드가 채워진 부스만. 멱등(upsert).
insert into booth_enrichment (
  booth_id, goods_keywords, theme_tags, summary, tips, source_url,
  value_tags, roam_interpretation, recommendation_reasons, things_to_do,
  timing, memory_hooks, conversation_prompts, confidence
) values
  ('b_a1001', '["문재인의 필사노트","독서노트","ZINE 행간과 여백"]'::jsonb, '["lit","humanities","general","art"]'::jsonb, '돌베개×평산책방 공동 부스 — 인문서와 문재인 추천도서', '혼잡 최상위·소요 30~60분. 2026 최대 화제 부스, 6/24 문재인 등장 수백 명 운집, 6/25 유시민·탁현민 즉석 북토크. ''대통령의 책'' 코너·필사노트.', 'https://psbooks.kr', '[{"slug":"learning","strength":0.9},{"slug":"trend","strength":0.8},{"slug":"social","strength":0.5}]'::jsonb, '유명인의 서재를 엿보듯, 한 사람의 독서 취향을 따라가며 인문서를 발견하는 부스야.', '{"learning":"추천도서 큐레이션을 따라가며 인문 주제를 깊게 파기 좋아.","trend":"올해 도서전에서 가장 화제인 부스라, 지금 뭐가 회자되는지 감이 와.","social":"즉석 북토크가 열려서 저자·독자와 같은 공기를 느낄 수 있어."}'::jsonb, '["추천도서 코너 훑기","필사노트 살펴보기","북토크 일정 확인"]'::jsonb, '["6/24 오후 문재인 등장 전후 인파 최대","북토크 시간대 밖이 여유로움"]'::jsonb, '["대통령의 서재","인문 큐레이션","화제의 부스"]'::jsonb, '["이 중에 네가 먼저 집어들 책은 뭐야?"]'::jsonb, 'high'),
  ('b_a104', '[]'::jsonb, '["children","lit","art"]'::jsonb, '감성 그림책 중심 아동·그림책 전문 출판사', '예상혼잡 중·소요 10~20분. 가족·유아 동반 관람객이 꾸준한 그림책 전문 중견사. 화제신간 ''매미와 늙은 소''·''초록을 좋아하는 고양이''.', null, '[{"slug":"rest","strength":0.75},{"slug":"discovery","strength":0.6},{"slug":"inspiration","strength":0.5}]'::jsonb, '아이랑 같이 왔거나 그림책 감성이 그리우면, 부담 없이 넘겨보기 좋은 부스야.', '{"rest":"감성 그림책이라 가볍게 넘겨보며 쉬어가기 좋아.","discovery":"''매미와 늙은 소''·''초록을 좋아하는 고양이'' 같은 화제 신간을 새로 만나볼 수 있어.","inspiration":"그림책 특유의 그림 감성이 마음을 말랑하게 해."}'::jsonb, '["화제 신간 그림책 넘겨보기","아이와 함께 고르기","그림 감상하기"]'::jsonb, '["가족·유아 동반이 꾸준해 주말 오후 붐빔"]'::jsonb, '["감성 그림책","매미와 늙은 소","가족 관람"]'::jsonb, '[]'::jsonb, null),
  ('b_a1101', '["캡슐 토이","듄","드래곤 라자","셜록 홈즈 전집"]'::jsonb, '["lit","general"]'::jsonb, '민음사 그룹·황금가지 공유 부스 — 문학·인문·SF/판타지 장르문학', '인지도 메이저·혼잡 상·소요 20~40분, 도서전 최고 인기 부스. 세계문학전집·캡슐토이 가챠로 결제 대기줄 혼잡. 듄·드래곤 라자 장르문학 팬덤.', 'https://instagram.com/minumsa_books', '[{"slug":"goods","strength":0.9},{"slug":"discovery","strength":0.7},{"slug":"trend","strength":0.6}]'::jsonb, '익숙한 이름값만 믿고 지나치기 아까운, 장르문학 팬심이 모이는 부스야.', '{"goods":"캡슐토이 가챠·세계문학전집 같은 소장각 굿즈가 많아.","discovery":"듄·드래곤 라자처럼 팬덤 두꺼운 장르문학을 한자리에서 파볼 수 있어."}'::jsonb, '["캡슐토이 가챠 뽑기","세계문학전집 구경","장르문학 신간 훑기"]'::jsonb, '["결제 대기줄이 길어 이른 시간대 추천","점심 직후 혼잡 절정"]'::jsonb, '["캡슐토이 가챠","장르문학 팬심","세계문학전집"]'::jsonb, '["가챠 뽑으면 뭐가 나오면 좋겠어?"]'::jsonb, 'high'),
  ('b_a1102', '["NFC 키링","위글위글 리유저블백","오디오북"]'::jsonb, '["humanities","lit","art"]'::jsonb, '윌라 운영 지식콘텐츠 기업·자기계발·경제경영 출판사', '인지도 중견·혼잡 상·소요 20~40분. 윌라·윌라스토리 공동 ''스토리 온에어'' 체험 부스. 오디오북 체험·라디오 포토존·NFC 키링. 윌라 낭독 콘서트+신소율 사인회.', null, '[{"slug":"experience","strength":0.85},{"slug":"goods","strength":0.6},{"slug":"social","strength":0.5}]'::jsonb, '귀로 듣는 책이 궁금하면, 오디오북을 직접 체험해보고 굿즈까지 챙기는 부스야.', '{"experience":"오디오북 체험·라디오 포토존처럼 직접 해볼 거리가 많아.","goods":"NFC 키링·리유저블백 같은 챙길 굿즈가 쏠쏠해.","social":"윌라 낭독 콘서트랑 신소율 사인회로 저자·성우를 가까이서 볼 수 있어."}'::jsonb, '["오디오북 체험하기","라디오 포토존 찍기","낭독 콘서트 시간 확인"]'::jsonb, '["신소율 사인회 시간대 인파 몰림"]'::jsonb, '["오디오북 체험","낭독 콘서트","NFC 키링"]'::jsonb, '[]'::jsonb, null),
  ('b_a1405', '[]'::jsonb, '["lit","humanities","art"]'::jsonb, '기독교·신앙 단행본 소형 출판사', '예상혼잡 하·소요 5~10분. 6개사 공동부스(A1405) 일부 테이블 규모의 신생 소형 기독교 출판사. 화제신간 ''믿지만, 거기까지''.', null, '[{"slug":"learning","strength":0.65},{"slug":"rest","strength":0.6},{"slug":"discovery","strength":0.55}]'::jsonb, '신앙과 삶의 질문이 궁금하면, 붐비지 않게 잠깐 들러 훑어보기 좋은 작은 부스야.', '{"learning":"기독교·신앙 주제를 차분히 파고들며 읽어보기 좋아.","rest":"혼잡이 낮아 5~10분이면 부담 없이 훑고 나올 수 있어.","discovery":"신생 소형 출판사라 화제신간 ''믿지만, 거기까지''처럼 새 목소리를 발견하게 돼."}'::jsonb, '["화제신간 ''믿지만, 거기까지'' 살펴보기","신앙 에세이 훑기","작은 출판사 목록 구경"]'::jsonb, '["혼잡 낮음·5~10분이면 충분"]'::jsonb, '["기독교·신앙","믿지만 거기까지","작은 출판사"]'::jsonb, '[]'::jsonb, null),
  ('b_a1703', '["NFC 메달 키링","크레마 전자책","한정 굿즈","경험 영수증"]'::jsonb, '["science","general","lit"]'::jsonb, '국내 1위 인터넷 서점·문화 콘텐츠 유통 플랫폼', '인지도 메이저·혼잡 상·소요 20~40분(체험 대기 포함). 개막 첫날 리딩런 약 1,700명. AI 낭독 체험·NFC 메달 키링·경험 영수증 포토존.', null, '[{"slug":"experience","strength":0.8},{"slug":"trend","strength":0.7},{"slug":"goods","strength":0.6}]'::jsonb, '책을 사는 것 말고도, AI 낭독 체험하고 포토존에서 놀 거리가 있는 부스야.', '{"experience":"AI 낭독 체험·포토존처럼 직접 해볼 거리가 많아.","trend":"개막 리딩런에 1700명이 몰릴 만큼 도서전 화제의 중심이야.","goods":"NFC 메달 키링·크레마·경험영수증 같은 챙길 굿즈가 있어."}'::jsonb, '["AI 낭독 체험하기","포토존에서 찍기","경험영수증 받기"]'::jsonb, '["개막 리딩런(1700명) 전후 인파 최대"]'::jsonb, '["AI 낭독","리딩런","경험영수증"]'::jsonb, '[]'::jsonb, null),
  ('b_a2102', '["팔각성냥","선향","복캔들","향"]'::jsonb, '["art","humanities"]'::jsonb, '한국 정서 재해석 디자인·아트북 출판 스튜디오', '예상혼잡 상·소요 15~30분. 향·색이름 352 등 인기 굿즈와 감각적 부스 연출로 긴 줄(2025년 별도 대기공간). 화제신간 ''산 239''.', null, '[{"slug":"inspiration","strength":0.85},{"slug":"goods","strength":0.75},{"slug":"discovery","strength":0.6}]'::jsonb, '한국적인 정서를 감각적으로 다시 푼, 향과 아트북으로 눈코가 즐거운 부스야.', '{"inspiration":"한국 정서를 재해석한 감각적 연출이라 보는 것만으로 영감이 와.","goods":"팔각성냥·선향·복캔들·향 같은 소장각 굿즈가 인기야.","discovery":"디자인·아트북 스튜디오라 흔치 않은 물건을 새로 발견하기 좋아."}'::jsonb, '["향·색이름352 구경","복캔들 골라보기","아트북 훑기"]'::jsonb, '["감각적 연출로 줄이 길어, 여유 있을 때 방문"]'::jsonb, '["한국 정서 재해석","향·색이름352","아트북"]'::jsonb, '[]'::jsonb, null),
  ('b_a2202', '["틴케이스·스티커 세트","문지북클럽 웰컴 키트","시집 서명본"]'::jsonb, '["lit","humanities"]'::jsonb, '창비와 함께 한국문학 2대 축, 순수문학 출판사', '메이저 부스, 혼잡 상·15~25분. 창립 50주년 골판지 도서관 부스가 SNS 인증 명소, 굿즈·시집 서명본·강연 운영(서명본 조기 품절 주의).', null, '[{"slug":"discovery","strength":0.75},{"slug":"goods","strength":0.7},{"slug":"inspiration","strength":0.6}]'::jsonb, '시와 순수문학을 좋아하면, 서명본 챙기고 골판지 도서관에서 사진 남기는 부스야.', '{"discovery":"문학과지성사 계열 순수문학이라 묵직한 시·소설을 새로 파보기 좋아.","goods":"시집 서명본·틴케이스·스티커 같은 소장각 굿즈가 있어.","inspiration":"창립 50주년 골판지 도서관 연출이 SNS 명소라 눈이 즐거워."}'::jsonb, '["시집 서명본 찾기","골판지 도서관 사진 찍기","틴케이스 굿즈 챙기기"]'::jsonb, '["서명본은 조기 품절, 이른 시간 추천"]'::jsonb, '["순수문학 서명본","골판지 도서관","창립 50주년"]'::jsonb, '[]'::jsonb, null),
  ('b_a2303', '["책갈피"]'::jsonb, '["art","humanities"]'::jsonb, '월간 ''디자인'' 펴낸 라이프스타일·디자인 출판 미디어 기업', '예상혼잡 중·소요 15~30분. 오뚜기 협업 ''Design Your Own Life'' 부스에서 6/24~28 상시 반려 갈피표 만들기·취향 테이블 꾸미기 체험 운영.', 'https://designhouse.co.kr', '[{"slug":"inspiration","strength":0.85},{"slug":"experience","strength":0.75}]'::jsonb, '디자인 감각을 눈으로만 보지 말고, 갈피표 만들고 취향대로 꾸며보는 부스야.', '{"inspiration":"월간 디자인이 큐레이션한 감각적인 물건과 지면을 실컷 볼 수 있어.","experience":"갈피표 만들기·취향 테이블 꾸미기처럼 손으로 해보는 체험이 있어."}'::jsonb, '["갈피표 만들기","취향 테이블 꾸미기","책갈피 챙기기"]'::jsonb, '["갈피표 만들기 체험은 대기 생길 수 있음"]'::jsonb, '["월간 디자인","갈피표 만들기","취향 테이블"]'::jsonb, '[]'::jsonb, null),
  ('b_a307', '[]'::jsonb, '["humanities","lit","children"]'::jsonb, '1988년 창립한 인문·교양·문학 중심 중견 종합 출판사', '인지도 중견·혼잡 중·소요 10~20분. 공지영·한비야·류시화 베스트셀러 보유. 2026 화제작 《다시 만난 세계》(김희교). 아동 임프린트 푸른숲주니어.', null, '[{"slug":"learning","strength":0.8},{"slug":"discovery","strength":0.6}]'::jsonb, '오래 쌓아온 인문·교양 목록을 천천히 훑으며 읽을 거리를 고르는 부스야.', '{"learning":"공지영·한비야·류시화 같은 인문·교양 목록이 두터워 깊이 읽기 좋아.","discovery":"화제작 《다시 만난 세계》부터 아동 임프린트까지 폭이 넓어 새로 파볼 게 있어."}'::jsonb, '["화제작 《다시 만난 세계》 살펴보기","인문·교양 신간 훑기","푸른숲주니어 아동책 구경"]'::jsonb, '["화제작 코너는 사람 몰릴 수 있음"]'::jsonb, '["인문·교양","다시 만난 세계","푸른숲주니어"]'::jsonb, '[]'::jsonb, null),
  ('b_a401', '["솔거나라 시리즈","까치호랑이","백두산 이야기"]'::jsonb, '["children","art","lit"]'::jsonb, '1976년 창립한 어린이 그림책 전문 출판사', '인지도 중견·혼잡 중·소요 15~25분. 그림책 1세대 대표 브랜드, 학부모·교사 충성도 높음. 백두산 이야기·달려 토토·솔거나라 시리즈.', 'https://instagram.com/borimbook', '[{"slug":"rest","strength":0.65},{"slug":"discovery","strength":0.6},{"slug":"learning","strength":0.55}]'::jsonb, '우리 옛이야기 그림책의 원조 격이라, 아이 책 고르는 어른이 믿고 찾는 부스야.', '{"rest":"익숙한 그림책들이라 가볍게 넘겨보며 쉬어가기 좋아.","discovery":"솔거나라·까치호랑이 같은 1세대 그림책의 뿌리를 다시 발견하게 돼.","learning":"우리 옛이야기·전통을 아이 눈높이로 배우기 좋아."}'::jsonb, '["대표 그림책 솔거나라 찾기","전통 그림책 넘겨보기","아이 책 고르기"]'::jsonb, '["학부모·교사 방문이 꾸준해 주말 붐빔"]'::jsonb, '["1세대 그림책","까치호랑이","옛이야기"]'::jsonb, '[]'::jsonb, null),
  ('b_a503', '["팝업북","컬러링북","도서전 한정 굿즈"]'::jsonb, '["lit","general","children"]'::jsonb, '해리포터·다빈치코드 등 해외 장르문학 강세 종합 출판사', '인지도 메이저·혼잡 상·소요 20~35분. 도서전 한정 굿즈 오픈런·조기 품절. 팝업북 전시 + 운명 뽑기 이벤트. 김영사·이야기장수 인접 입구권.', null, '[{"slug":"goods","strength":0.85},{"slug":"experience","strength":0.65},{"slug":"trend","strength":0.55}]'::jsonb, '해리포터·다빈치코드 팬이면, 한정 굿즈 오픈런하고 팝업북 구경하는 부스야.', '{"goods":"팝업북·컬러링북·한정 굿즈가 많아 소장 욕구를 자극해.","experience":"팝업북 전시랑 운명뽑기처럼 직접 해볼 거리가 있어.","trend":"한정 굿즈 오픈런이 벌어질 만큼 화제인 부스야."}'::jsonb, '["한정 굿즈 오픈런","팝업북 전시 구경","운명뽑기 해보기"]'::jsonb, '["한정 굿즈 오픈런·조기 품절, 개장 직후 방문"]'::jsonb, '["해외 장르문학","한정 굿즈 오픈런","팝업북"]'::jsonb, '[]'::jsonb, null),
  ('b_a901', '["더클래식 세계문학","걸 클래식 컬렉션","빅팻캣 시리즈"]'::jsonb, '["lit","humanities","art"]'::jsonb, '에세이·어학·클래식 컬렉션 강세 종합 출판사', '인지도 중견·혼잡 중·소요 15~25분. 수전 손택·사노 요코 등 두터운 독자층. 정관스님 ''나의 음식'' 북토크 예정. 신간 영화에 관하여.', 'https://instagram.com/willbooks_pub', '[{"slug":"learning","strength":0.75},{"slug":"discovery","strength":0.6},{"slug":"social","strength":0.55}]'::jsonb, '에세이부터 고전·어학까지 폭넓게 훑으며 읽을 거리를 고르는 부스야.', '{"learning":"수전 손택·사노 요코 같은 묵직한 에세이와 클래식으로 깊이 읽기 좋아.","discovery":"에세이·어학·클래식이 두루 있어 취향 밖 책도 새로 발견하기 좋아.","social":"정관스님 북토크로 저자의 이야기를 직접 들어볼 수 있어."}'::jsonb, '["클래식 시리즈 구경","에세이 신간 훑기","정관스님 북토크 시간 확인"]'::jsonb, '["정관스님 북토크 시간대 사람 몰림"]'::jsonb, '["에세이·클래식","수전 손택","정관스님 북토크"]'::jsonb, '[]'::jsonb, null),
  ('b_a903', '[]'::jsonb, '["lit","science"]'::jsonb, '동아시아 출판사의 SF 전문 임프린트', '예상혼잡 상·소요 15~30분. 김초엽·천선란 등 스타 SF 작가 팬덤으로 신간 코너 혼잡. 화제신간 ''새벽''(옥타비아 버틀러)·''토막 난 우주를 안고서''.', null, '[{"slug":"discovery","strength":0.8},{"slug":"trend","strength":0.75},{"slug":"learning","strength":0.5}]'::jsonb, '지금 한국 SF가 어디까지 왔는지 궁금하면, 스타 작가들 신간이 모이는 부스야.', '{"discovery":"동아시아 SF를 파고드는 임프린트라 새로운 작가·세계관을 발견하기 좋아.","trend":"김초엽·천선란처럼 지금 제일 회자되는 SF 신간이 다 모여 있어.","learning":"SF로 사고실험하듯 세계를 넓혀볼 수 있어."}'::jsonb, '["화제신간 훑기","김초엽·천선란 신간 찾기","SF 세계관 파보기"]'::jsonb, '["스타 작가 신간대는 인파 몰림"]'::jsonb, '["한국 SF","김초엽·천선란","화제신간"]'::jsonb, '[]'::jsonb, null),
  ('b_b471', '["대만 독립출판","아시아 독립출판"]'::jsonb, '["art","lit","humanities"]'::jsonb, '대만 독립·1인 출판사 40여 곳 연합 공동 부스', '인지도 독립·혼잡 중·소요 15~25분. 신설 국제 독립출판 구역, 2026 테마 「讀字藥局(독서 처방)」. 개방형 소형 부스라 피크 시 정체.', 'https://indiepublisher.tw', '[{"slug":"discovery","strength":0.9},{"slug":"inspiration","strength":0.65},{"slug":"social","strength":0.5}]'::jsonb, '국내에선 보기 힘든 대만·아시아 1인 출판을 한자리에서 파보는 부스야.', '{"discovery":"대만·아시아 독립출판 40여 곳이 모여 새로운 책을 발견하기 딱이야.","inspiration":"「독서 처방」 테마 연출이 독특해 감각적 자극이 있어.","social":"1인 출판 제작자들과 직접 이야기 나눠볼 수 있어."}'::jsonb, '["대만 독립출판 훑기","독서 처방 받아보기","제작자에게 말 걸기"]'::jsonb, '["신설 국제 독립출판 구역이라 초반엔 한산"]'::jsonb, '["대만 독립출판","독서 처방","1인 출판"]'::jsonb, '[]'::jsonb, null),
  ('b_b602', '["시 필사노트","마스킹테이프","한지부채","블라인드북"]'::jsonb, '["lit","humanities","general","children"]'::jsonb, '10여 개 임프린트 보유한 문학 전문 대형 출판그룹', '예상혼잡 상·소요 20~40분, 대기 10~30분+. 사인회 6/24 최은영·6/26 김영하·6/27 은희경·6/28 김애란 등, 한정 리커버·굿즈 다수.', 'https://munhakdongne.com', '[{"slug":"social","strength":0.9},{"slug":"goods","strength":0.8},{"slug":"trend","strength":0.6}]'::jsonb, '좋아하는 작가 사인 받고 한정 굿즈까지 노리는, 문학 팬이라면 오래 머물 부스야.', '{"social":"최은영·김영하·은희경·김애란 사인회가 줄줄이라 좋아하는 작가를 직접 만날 수 있어.","goods":"시필사노트·한지부채·블라인드북 같은 한정 굿즈가 다양해.","trend":"화제 작가 사인회로 도서전에서 가장 사람 몰리는 축이야."}'::jsonb, '["사인회 일정 확인","블라인드북 골라보기","한정 리커버 챙기기"]'::jsonb, '["사인회 시간대 대기 10~30분+","인기 작가 사인회 전 미리 줄서기"]'::jsonb, '["작가 사인회","한정 리커버","블라인드북"]'::jsonb, '[]'::jsonb, null)
on conflict (booth_id) do update set
  goods_keywords = excluded.goods_keywords,
  theme_tags = excluded.theme_tags,
  summary = excluded.summary,
  tips = excluded.tips,
  source_url = excluded.source_url,
  value_tags = excluded.value_tags,
  roam_interpretation = excluded.roam_interpretation,
  recommendation_reasons = excluded.recommendation_reasons,
  things_to_do = excluded.things_to_do,
  timing = excluded.timing,
  memory_hooks = excluded.memory_hooks,
  conversation_prompts = excluded.conversation_prompts,
  confidence = excluded.confidence,
  updated_at = now();
